
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import './globals.css';

const myFonts = Roboto_Mono({
    subsets: ['latin'],
    display : "swap",
    weight: ['400']

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFonts.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
